on:
  push:
    branches:
      - 'main'
      - 'dev'
      - 'build/1201814544319626_apk-build-support'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'dev'

name: Test, Build and Release apk
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    container:
        image: cirrusci/flutter:2.5.3
    steps:
    - uses: actions/checkout@v1
    # - uses: actions/setup-java@v1
    #   with:
    #    java-version: '12.x'
    #- uses: subosito/flutter-action@v1
      #with:
       # flutter-version: '1.7.8+hotfix.4'
    - run: flutter clean
    - run: flutter pub upgrade
    - run: flutter doctor -v
    - run: flutter pub get
    #- run: flutter test
    - run: flutter build apk
    - run: ls -R 
    #--debug --split-per-abi
    - name: set env
      run: echo "NOW=$(date +'%Y.%m.%d')" >> $GITHUB_ENV
   # - name: Push APK to Releases
      #uses: ncipollo/release-action@v1
    #  uses: "marvinpinto/action-automatic-releases@latest"
     # with:
        #artifacts: "build/app/outputs/flutter-apk/app-release.apk"
        #token: ${{ secrets.TOKEN }}
     #   repo_token: "${{ secrets.TOKEN }}"
     #   automatic_release_tag: "${{ env.NOW }}"
      #  prerelease: false
      #  title: "${{ env.NOW }}"
      #  files: |
      #   build/app/outputs/flutter-apk/app-release.apk
    - name: release-apk
      uses: actions/upload-artifact@v2
      with:
        name: app-release.apk
        path: build/app/outputs/flutter-apk/app-release.apk
    - name: Releasing using Hub
      uses: kyze8439690/action-release-releaseapk@master
      env:
       GITHUB_TOKEN: ${{ secrets.TOKEN }}
       APP_FOLDER: build/app